name: Language Statistics

on:
  workflow_dispatch:
  schedule:
    # Runs at 12am EAT
    - cron: '0 2 * * *'

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - name: Set commit message
        id: set_commit_message
        run: echo "COMMIT_MESSAGE=Update the Graph with new Metrics on $(date +"%Y-%m-%d")" >> $GITHUB_ENV

      - uses: ryuanerin/top-languages-readme@master
        with:
          COMMIT_MESSAGE: ${{ env.COMMIT_MESSAGE }}
          LINE_FORMAT: "$NAME   $SIZE $BAR  $PERCENT"
          BLOCKS: "⣀⣄⣤⣦⣶⣷⣿"
          BAR_WIDTH: 25
          SHOW_TOTAL: true
          SHOW_TOTAL_SEPARATOR: true
