name: Top-Languages Readme

on:
    workflow_dispatch:
    schedule:
        # Runs at 12am UTC
        - cron: '0 * * * *'

jobs:
    update-readme:
        name: Update this repo's README
        runs-on: ubuntu-latest
        steps:
        - uses: ryuanerin/top-languages-readme@master
          with:
            COMMIT_MESSAGE: "Update the README.md graph with the latest data" 
            LINE_FORMAT: "$NAME   $SIZE $BAR  $PERCENT" 
            BLOCKS: "⣀⣄⣤⣦⣶⣷⣿" 
            BAR_WIDTH: 25 
            SHOW_TOTAL: true 
            TOP_TOTAL: false 
            SHOW_TOTAL_SEPARATOR: true 
