name: Language Statistics

on:
    workflow_dispatch:
    schedule:
        # Runs at 12am UTC
        - cron: '0 0 * * *'

jobs:
    update-readme:
        name: Update this repo's README
        runs-on: ubuntu-latest
        steps:
        - uses: ryuanerin/top-languages-readme@master
          with:
            GH_TOKEN: ${{ secrets.GH_TOKEN }}
            COMMIT_MESSAGE: "Update the Graph with new Metrics"
            DONE_BLOCK:  "█"
            EMPTY_BLOCK: " "
            LIST_COUNT:  10
            HIDE_SIZE: false
