name: Languages Graph

on:
    workflow_dispatch:
    push:
      branches:
        - master
    schedule:
        # Runs at 12am UTC
        - cron: '0 0/3 * * *'

jobs:
    update-readme:
        name: Update the README
        runs-on: ubuntu-latest
        steps:
        - uses: gekkowrld/langs-readme@gekkowrld
          with:
            COMMIT_MESSAGE: "Update the README.md language graph on `date` with the latest data" 
            LINE_FORMAT: "$NAME   $SIZE $BAR  $PERCENT" 
            BLOCKS: "⣀⣄⣤⣦⣶⣷⣿" 
            BAR_WIDTH: 25 
            SHOW_TOTAL: true 
            TOP_TOTAL: false 
            SHOW_TOTAL_SEPARATOR: true 
